name: 5. Sync Upstream
run-name: Sync Upstream (${{ github.ref_name }})

on:
  schedule:
    - cron: '0 3 * * *'
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      actions: write

    steps:
      - name: Sync Fork with Upstream
        uses: Artificial-Pancreas/sync-upstream-repo@master
        with:
          upstream_repo: https://github.com/Artificial-Pancreas/iAPS.git
          upstream_branch: ${{ github.ref_name }}
          downstream_branch: ${{ github.ref_name }}
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch_args: ""
          merge_args: ""
          push_args: ""
          spawn_logs: "false"
